### ISSUE TITLE
Add `currentUser` to application state via Apollo

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#112]
#### Perceived Problem

- Currently, in order to get the `currentUser` we have to call that query in whichever component needs it.
- It is currently being fetched in the Nav, but we don't even have the ability to pass that to other pages.

#### Ideas / Proposed Solution(s)

- Build out our application state to make this available via Apollo

**Comment by nlitwin** [comment]
Looks like I'll need this for the profile page, so I'll grab it :)

**Comment by robin-macpherson** [comment]
> Looks like I'll need this for the profile page, so I'll grab it :)

Absolutely smashing kind sir!
