### ISSUE TITLE
Audit design system colors

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#125]
Originally opened just for button hover state, expanded to audit colorscheme across the board. Feel free to edit and expand as things are found pending audit.

- [ ] Secondary button hover state is low contrast
  ![Screen Shot 2020-07-01 at 9 52 53 PM](https://user-images.githubusercontent.com/2343714/86311167-5cf9c880-bbe5-11ea-89df-c1314753be5c.png)

**Comment by nlitwin** [comment]
The button colors and hover colors are intentionally bad because we need to do a full audit on our design system's colors still 😄 We could expand this task to include figuring out what our colors are in the design system and then fixing the buttons should be pretty straightforward

**Comment by Lanny** [comment]
ahh, cool. Normal state looks great to me so I didn't realize it was a WIP heh, will update issue

**Comment by robin-macpherson** [comment]
In my opinion we shouldn't have things like this for the moment that look intentionally bad, just given the situation we're in with time. I think that if there are things we need to use right now, we should try to make them look fine based on our existing stuff and get everything working. I already created a color palette way back and we can make some adjustments for small things we need and just do our best, then update things to be tighter afterwards, at least after going into beta.

**Comment by robin-macpherson** [comment]
I think I've covered this now 🙂
