### ISSUE TITLE
Invalid password on logic page throws up Apollo error modal

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#152]
Should show a form error without apollo freaking out.

**Comment by Lanny** [comment]
Looks like this only happens in dev, guess the apollo in-DOM error reporting isn't enabled in dev and error messaging happens as you'd expect. So this is probably low priority, if it's an issue at all. @robin-macpherson

**Comment by robin-macpherson** [comment]
> Looks like this only happens in dev, guess the apollo in-DOM error reporting isn't enabled in dev and error messaging happens as you'd expect. So this is probably low priority, if it's an issue at all. @robin-macpherson

Oooh good find! Got it thanks @Lanny
