### ISSUE TITLE
FEATURE: Onboarding Modal!

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#173]
#### Perceived Problem

- Many things require a user to have their native language and the languages that they are learning to be listed.
- Currently, the only way for the user to update that info is to go to the `settings` page and find that spot.

#### Ideas / Proposed Solution(s)

- A short-term solution could be to re-direct them to that page after signup, but this will make them skip right over the most beautiful and "wow" moments like seeing the feed for the first time, for example.

## BOOM! 💥
- @nlitwin wrote a super super nice modal that we haven't used yet, but it's all in place, easy to implement, and works beautifully.
- Let's build an onboarding flow so that after a user logs in, they see a simple modal that guides them through adding that essential info! It can be friendly and approachable, showing that most fields are optional and they can come back to them later in 'settings', but the main thing we need to provide them with a great experience is their language info

#### Helpful notes

- All of the logic is already in place on the backend for updating language info. Please see the current `settings > languages` section to see how this is implemented end to end

**Comment by robin-macpherson** [comment]
cc: @nlitwin @Lanny

**Comment by nlitwin** [comment]
@robin-macpherson This sounds great! Just to clarify, would the flow look something like this?

1. User creates account
2. User lands on the my feed page
3. If the user hasn't seen the modal before (check local storage, perhaps), show them the modal (maybe 5 seconds after having landed on the page and not immediately?)
4. User sees a modal with a form in it to add native and learning languages + info about being able to add them on the settings page
5. User submits form with language info
    - after success, some text in the modal lets the user know it was successful, e.g. "Thanks for adding your languages!"
6. Whether use adds language or closes the modal without submitting, we mark that user as having seen the modal in local storage
