### ISSUE TITLE
EDITOR: An exception is thrown when typing first character in Chinese or Japanese

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#194]
#### Description

When typing the first character in Japanese or Chinese, upon making your final selection, the frontend explodes and lies to you showing a 404/500 combo error page!

![image](https://user-images.githubusercontent.com/34203886/88950665-cc48f380-d249-11ea-81a9-fae7e44c4aeb.png)

#### Repro Steps

1. Go to "new post'
2. Start typing one character
3. Make selection (hitting '1' for example)
4. 💥 💻

**Comment by Lanny** [comment]
Relates to upstream issue in slate (possible upstream issues in chromium): https://github.com/ianstormtaylor/slate/issues/3686

Would be best for us to fix at the slate level, but linked ticket suggests we may be able to patch around it. Possible just disabling placeholder text would be a sufficient bandaid, but that needs to be tested
