### ISSUE TITLE
We need "toast messages" 

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#251]
#### Perceived Problem

- Some users have reported the lack of feedback to confirm an action has been successfully done

#### Ideas / Proposed Solution(s)

- I think we should add little toast messages for actions where you stay on the same page and/or it's not obvious

#### Open questions

- Library?

**Comment by robin-macpherson** [comment]
@nlitwin how large of an effort do you think this would be?

**Comment by nlitwin** [comment]
This isn't too bad to implement, should be about a days worth of effort methinks

**Comment by robin-macpherson** [comment]
@nlitwin Awesome! Think you can add this to your list? 🙏🏼
