### ISSUE TITLE
🐞 More visual bugs with post cards

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#322]
#### Description

Post cards appear differently depending on their content. Post cards should be fixed and consistent, no matter how long the post is or any other content. Proportions seem to still be off when there is content.

![image](https://user-images.githubusercontent.com/34203886/91384137-b7c53000-e7e2-11ea-9e55-613a36a83f7f.png)

**Comment by nlitwin** [comment]
@robin-macpherson I think what you're seeing is that the `excerpt` can be one to several lines of text, depending on the content. I remember noticing that when I was originally building out the `PostCard`s and I mentioned it to you that this would be the case until we had a line clamp to fix each excerpt to a specific number of lines. If you want to take a look at #320, I think it remedies the situation. It would fix the proportions described in #321 as well
