### ISSUE TITLE
Dashboard Nav should be delightfully animated and responsive

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#35]
#### Perceived Problem

- Dashboard navigation looks great on wider screens but currently lacks responsiveness for mobile screens or even smaller laptops
- Users may want to have a totally minimalistic writing experience without being distracted by the wider nav
- We have some parts of the dashboard, such as `settings`, that actually require a narrower nav bar (see design B)

#### Ideas / Proposed Solution(s)

- Create a responsive system that allows users to manually collapse & expand the nav
- It should expand and collapse automatically based on screen width, while still being able to be toggled by the user
- Collapsing and expanding the nav should be delightfully and simply animated 👌🏼😌
- This isn't currently present in the designs, but it might be nice to have a nice double-chevron in our `brandBlue` color that allows them to manually toggle it open and closed. Just as a thought. Notion has a nice implementation of this! (see design C)

#### Designs

**A** - Here's how the nav looks at full width
![image](https://user-images.githubusercontent.com/34203886/78315498-0a3f4080-7512-11ea-86d7-28d70c75584c.png)

**B** - Here's how it looks collapsed
![image](https://user-images.githubusercontent.com/34203886/78315507-13301200-7512-11ea-97a3-ff4c2b60e30a.png)

**C** Here's how Notion has that nice little double chevron toggle:
![image](https://user-images.githubusercontent.com/34203886/78315669-8b96d300-7512-11ea-9acf-d7c8ddfa2db8.png)
![image](https://user-images.githubusercontent.com/34203886/78315672-8df92d00-7512-11ea-8225-23b0e676b386.png)

**Comment by robin-macpherson** [comment]
@nlitwin what do you think about taking a look into Framer vs. React Spring for animations? Also, do you think we should kind of ignore that question for now and potentially create something later using both and evaluate in time which (if any) feels like the best option?

**Comment by nlitwin** [comment]
@robin-macpherson I think those libraries are good potential options if we want to have really complex animations that require JS to work, but I hesitate to use a library for transitions/animations that can be done with CSS, like in the case of the dashboard nav
