### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#375]
#### Perceived Problem

- Title says it all for now. Creating the issue so it's documented and we can have further discussion on the technical design.

#### Discussion Points

- Do we want to use CircleCI?
- Cost

#### Ideas / Proposed Solution(s)

- ...

**Comment by Lanny** [comment]
Used CircleCI at work, and TravisCI for a personal project. Probably know a little more about circle at this point. Both offer a free tier, circle charges $30 as their first paid tier, travis is $69 at their first paid level.

The funky thing with Circle seems to be that the free tier has unlimited users, your upper bound is compute credits (based on this: https://circleci.com/docs/2.0/credits/ the free tier gets you 250 minutes of build time per week) with no way to pay for more. Then when you go up to the paid tier you pay per seat at $15 a person, plus $15 per 2.5k credits. They also have an open source offering which I believe we quality for which gets you a very nice 400k credits per month and it looks like also unlimited seats (what with it being for OSS) but I don't know if we have to apply for that or need to license in a particular way.

Travis has unlimited seats at any tier, instead you pay for concurrent jobs. I think with the volume of activity we have the free 1 concurrent job would get us a long way.

FWIW I know our circle bill at work is pretty steep, but obviously it's a much bigger org and can't take advantage of the OSS plan there.

My two cents would be we should check out the circle open source option, if we can get it then we can go with that, it seems like a good deal and we have a little more familiarity with it. If not I think Travis will probably take us further before we have to start forking over money.

**Comment by robin-macpherson** [comment]
Awesome thanks @Lanny ! Sounds like a good plan to me. I had basically the same thoughts but didn't know about the open source option for Circle and it's super helpful having all the exact numbers. I can try to make some time to look into what is required for the open source option
