### ISSUE TITLE
Reorg repo to have more consistent directory structure

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#400]
Right now the root level of the repo has a big ole mix of conceptual levels of code, some example of inconsistencies:

- `nexus` contains pretty much all the "backend" logic
- The "frontend" code is spread across `lib`, `elements`, `generated`, `graphql`, `components`, `config`, `hooks`, `theme`, `utils`, and `pages`
- `j-db-client` and `j-mail` are entirely separate deployments
- `docs` and `cypress`, while sparse, should probably be above everything else

Here's a proposed organization, totally open for discussion:

- ROOT
  - packages
    - j-mail
    - j-db-client
    - web
      - components
        - (all the existing stuff in components)
        - (all the stuff in elements, the components/elements separation never made a lot of sense to me)
      - pages
      - nexus
      - utils
        - (all the existing stuff in the top level utils)
        - i18n.js (moved from config, kill that dir)
      - generated (should probably get this out of source control at some point)
      - hooks
      - lib
      - public
      - scripts(or at top level?)
      - styles
      - theme
      - tsconfig.json
      - vercel.json
      - next*
      - codegen.yml
  - docs
  - cypress
  - README.md
 
We'll need to see if we can get vercel to deploy with the vercel stuff not being at the root dir, and some of the circle jobs will need to be re-written.

We could also consider a harder separation of the FE and BE (we ended up merging the two for deploy reasons, we could revisit and see if what we've learned in the last several months makes this surmountable) but I don't think it's a big deal either way.

**Comment by robin-macpherson** [comment]
We've talked about this in person but for visibility just a quick comment to say I think this makes a lot of sense and especially for new contributors I think this will make digesting the codebase and structure of things far more intuitive. I'm also fine with just consolidating `elements` and `components`

**Comment by robin-macpherson** [comment]
One more note, we've confirmed that Vercel has now added the option for setting the base directory for running deployment scripts, etc. so that removes the main blocker we had before while we're still on Vercel for now.
