### ISSUE TITLE
ERROR: column "resetTokenExpiry" cannot be cast automatically to type integer

### ISSUE THREAD

**Issue by davidsonsns** [Journaly/journaly#408]
#### Description

After runs `npm run prisma:generate` I'm getting an annoying database error that is blocking me to start contributing.

![Screen Shot 2020-12-31 at 08 48 11](https://user-images.githubusercontent.com/9276511/103409584-460d4200-4b46-11eb-9aa1-65717b036aa3.png)

#### Repro Steps

Following the [Initial Setup](https://github.com/Journaly/journaly#initial-setup) instructions, it's happening in the fourth step.

FYI: I thought that it was happening because I was running my Postgres through a docker image. But, to make sure that it hadn't any relation to it I installed Postgres on my host machine and it still happening.

#### Versions
- postgres (PostgreSQL): 13.1
- npm: 7.0.14
- node: v15.3.0
- OS: macOS Catalina

**Comment by Demezis** [comment]
I had the same problem.

Temporary fix:
You can drop column `resetTokenExpiry` and create it again with correct type and proceed with migration.

**Comment by davidsonsns** [comment]
@Demezis just created a PR fixing it. Let's way someone reviews it. Anyways, thanks for your feedback! 👍

**Comment by robin-macpherson** [comment]
Hi @davidsonsns ! Thanks for posting this, sorry for the delay things have been a little bit crazy with the launch, I will make some time to give feedback tomorrow as soon as I can! Thank you for your patience!

**Comment by davidsonsns** [comment]
@robin-macpherson thanks for your answer! 

FYI: Just come here from your YouTube channel. Let's rock!
