### ISSUE TITLE
🐞🚨 PostComment Subscriptions Not Working Properly

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#410]
#### Description

A lot of users are complaining about being notified of the `PostComment` that they authored themselves. It appears the problem is larger, though, because I just noticed I was not notified about some activity on a post that I commented on either.

#### Repro Steps

1. Leave a post comment and see that you are the one who gets notified
2. Leave another comment as another user and see that your original user who should be subscribed isn't notified

**Comment by Lanny** [comment]
Fixed with #414
