### ISSUE TITLE
Better Commenting Experience/Formatting

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#425]
#### Perceived Problem

- Currently, our comments are incredibly basic and a number of users have requested better options, in particular for our comments to respect line breaks, bold, underline, and italics.

#### Ideas / Proposed Solution(s)

- Respect line breaks inside of comments
- Limited formatting with markdown
  - support bold, italic, underline
  - maybe a tooltip or instructions?

#### Notes

- We may want to implement the same Rich Text editing experience as with our Slate editor in the future, but in the short-term markdown seems like a far simpler solution
- When looking into a library for markdown support, it would be great to find one that support Ruby Text

**Comment by robin-macpherson** [comment]
Just saw this inside of Jira at work while creating a new ticket, as an example of one approach for inserting some simple instructions as placeholder text:

![image](https://user-images.githubusercontent.com/34203886/103803809-f2976a00-5005-11eb-874e-1093547f65e6.png)

**Comment by davidsonsns** [comment]
@robin-macpherson as we talked before, can you assign it to me?

If so, I'd like to know if you guys have some markdown lib in mind? Saw that you mentioned using some lib to implement this feature. But, I do believe that it can be a little weird to follow using different approaches. I was thinking to implement slate here also, but more generic, I mean with fewer features than post body descriptions.

Let me know your thoughts about it.

**Comment by robin-macpherson** [comment]
Hi @davidsonsns , done! 😄

Yes so we were originally thinking that adding a simpler/more generic implementation of our Slate editor here would be the optimal/most desired solution, but it seems like quite a big project so were were thinking that in the short-term some simple markdown support might be a smaller/easier task.

However you've now worked quite a lot on the J-Editor and have gotten quite familiar with it, and so I would say that if you are excited about working on that first-choice solution here, let's do it! 💪🏼🔥

**Comment by robin-macpherson** [comment]
@Lanny @davidsonsns my only concern about implementing a lighter version of J-Editor here with Slate is that we do still have some pretty nasty bugs that are really unfortunate and mostly due to upstream issues that we still need to figure out how to solve for our users... so this solution would mean that all those impacted users (anyone writing in Korean or Chinese, for example) would now potentially experience those bugs in the commenting experience.

However, I think we should be striving for the best solutions whenever possible and this would be inline with our general philosophy of building for the best long-term code quality, functionality, and User Experience which is all great. But I think this needs to be at least brought up before we commit to that solution

**Comment by davidsonsns** [comment]
@robin-macpherson 
Gotcha! Is there any issue related to these bugs in the current editor? I'd like to propose fixing it before moving forward with any editor improvements/implementations.

I'll be happy to help to fix it 💪🏼

**Comment by Lanny** [comment]
@davidsonsns 

#479 is the last time IME issues were reported and has links to other issues for context. Think the last really terrible bug is repeated character entry on Android (iOS/mac Safari issues _should_ be fixed) which is what that ticket describes. To fix that I forked slate until fixes merge upstream, so I'd work off of this repo/branch: https://github.com/Journaly/slate/tree/journaly-patch

It would be super awesome to get this fixed but it's potentially a deep bug, and may end up requiring deubbing on a device or emulator. Which is just to say we really appreciate you taking a look but if it ends up being a rabbit hole then by all means feel free to say so and we can put it back in the backlog.

The only thing I'm a little concerned about in terms of the general approach of using slate here is the performance of creating and destroying slate instances on the fly. It's entirely possible that it's not a problem, but I think it would be worthwhile testing (espescially on lower end mobile devices that don't necessarily have the strongest CPUs) what the impact to responsitivity of opening/closing comment threads is.

**Comment by davidsonsns** [comment]
@Lanny I'll try to take a look ASAP at this issue related to Korean characters. It will be great to fix any current slate issue before making any improvement assigned to text experiences. I'll keep you all up to date. 🙂

**Comment by robin-macpherson** [comment]
Thanks so much for looking into this @davidsonsns , it's really been worrying us for quite a while now so if we can find a fix that would be absolutely amazing 💪

**Comment by robin-macpherson** [comment]
Hi @davidsonsns ! 👋🏼 I hope you are doing well my friend! 😊 I just wanted to check in on this ticket since it's been a couple of months now and this feature will be a big priority coming up. Are you still planning to work on it or shall we take this now? 

Also just so you're aware, we just updated our custom Slate build with #560

**Comment by davidsonsns** [comment]
hey @robin-macpherson. i'm so sorry bro! definitely lost track of time. many things happening 🙏🏻
unfortunately, i won't be able to help u guys with this one. hope to be able to help u guys ASAP, really missing contributing to the Journaly project.

see ya and take care

**Comment by robin-macpherson** [comment]
@davidsonsns thanks for the reply! No worries, I totally understand that life happens 😄 We'll take this one then and we will look forward to having you back in the future whenever you're ready! 😊 I hope you are well, friend!

**Comment by meredithcat** [comment]
It looks like the `react-markdown` library works pretty well for formatting comments in markdown! Here are some screenshots of the text itself & the generated HTML markup - we would just need to add some more styles to make sure that things get rendered properly inside of comments:

![Screen Shot 2021-08-03 at 9 06 45 PM](https://user-images.githubusercontent.com/351124/128120757-5d528d37-294d-4acf-a821-e1e7c4f23419.png)
![Screen Shot 2021-08-03 at 9 07 04 PM](https://user-images.githubusercontent.com/351124/128120780-4920bd51-f809-4bd1-a8fd-3d3846d5b715.png)

Now, for the editing experience. There are a couple of approaches we could take, roughly in order from easiest to hardest:

1. Give a placeholder text with some hints (e.g. `You can use Markdown here! Try using **bold**, *italic*...`)
1. Put a "Formatting Guide" link that gives a pop-up modal with markdown syntax (I think reddit does this?)
1. Create some buttons for bold, italic, etc that format the highlighted text when clicked. This one seems like it'd be the trickiest to implement, unless we want to use another library, and maybe not worth it.

@robin-macpherson Which would you advise?
