### ISSUE TITLE
Setup documentation references the wrong prisma folder.

### ISSUE THREAD

**Issue by JoshuaBelden** [Journaly/journaly#426]
Thank you @robin-macpherson  and other contributors for making such a great app. I hope I will be able to contribute in some small way.

I've gone through the `README.md` doc and have the app up and running locally. I did run into a small issue though with prisma and the environment file. Under the **Architecture** section, it mentions the model lives under `prisma/schema` which didn't exist in my project, even after running `npm ci`.

Under the `Initial Setup` it instructs you to create a `.env` file based on the `.env.example` file. Later it instructs you to run `npm run migrate:up`. When I ran that, I received the following error:

```
Get config 
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   | 
```

After reviewing the error, I realized that the package `j-db-client` creates a folder by the same name. There I finally found the prisma folder mentioned earlier. I copied my `.env` file into `j-db-client/prisma` but got the same error.

Once I moved my `.env` file to the root of the `j-db-client` folder, the database was created and the app launched without any other issues.

I think that we need to update the language of the instruction to include a mention of the `j-db-client` folder and instruct the developer to copy the `.env` file to the root of that folder.

I'm new to prisma though, so it's entirely possible I messed something up.

**Comment by robin-macpherson** [comment]
Hi @JoshuaBelden , thank you for the issue! Yes we've had a few major structural changes in the codebase, among those was breaking all of our Prisma stuff out into an internal database client/package and I need to update the `README.md`. I'm glad that you were able to get everything up and running, though! Sorry for all the extra discovery work you had to do.

I'll try to get to this ASAP

**Comment by JoshuaBelden** [comment]
@robin-macpherson If you create an issue and assign it to me, I'd be happy to clean this up and submit a PR for it.

**Comment by robin-macpherson** [comment]
Thank you @JoshuaBelden that would be very helpful! Right now we're heads down in a couple of important infrastructure projects (currently e-mail batching and then a new micro-service around image uploading to drastically reduce our costs on both fronts) so having this taken care of would be a huge help!

I just created #430 for you and added some information to help out, I also referenced the email batching PR in case that also helps, but I will also try my best to do a better job of updating documentation as things change. I think the project is gradually getting to a much more stable place and where this will be easier - right now the email batching is just such a huge priority so we stop bombarding users with notifications so it's been a bit of a rush.

Thanks so much and please let me know if you need any more info to complete this! 🙏🏼

p.s. for some reason I can't assign or tag you in the issue I created, can you try commenting on the issue?

**Comment by JoshuaBelden** [comment]
I can comment on issues, but I believe without being a contributor, I'd need specific push access to the repo, which wouldn't be right at this point. I will make the fix in my repo and push a PR. I believe I can then associate the issue to that PR so it at least shows there's a fix in place.
