### ISSUE TITLE
Update Documentation/README

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#430]
## Description

We've had a few significant structural changes in the codebase in quite quick succession and so the docs have become out-of-date. In that time, we've had new contributors join the project and it's been challenging to get started with the outdated docs.

Closes #426

### Changes

- **j-db-client:** we moved all of our Prisma code out into an internal package so that we could import that into various micro-services (such as J-Mail for emailing) that need to interact with the database.
- **j-mail:** emails are now handled by a serverless micro-service that is all a part of our AWS cloud infrastructure, which consists of a managed queue with (SQS) and Lambda. This is currently being further updated in #417 as we build out email batching.
- **.env:** I think our instructions around the `.env` file have always been a little confusing. You should be able to have a `.env` at the root level of the project, but depending on how you're running things it can be helpful to have one in `j-db-client` as well. We could update the example files

### Other notes

- The workflow with `j-db-client` is that we actually have scripts that can be run from the top-level project to make things less confusing now, so to generate or run migrations developers can still just run `npm run migrate:save` or `npm run migrate:up` from the top level
  - To make DB changes, first edit the `schema.prisma` file as needed
  - Then, in the project root, run `npm i @journaly/j-db-client` which will re-install the library and will also run the post-install hook that generates the Prisma Client

**Comment by JoshuaBelden** [comment]
I can comment on issues, but I believe without being a contributor, I'd need specific push access to the repo, which wouldn't be right at this point. I will make the fix in my repo and push a PR. I believe I can then associate the issue to that PR so it at least shows there's a fix in place.
