### ISSUE TITLE
Use Optimistic UI for giving "thanks" on comments

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#434]
#### Perceived Problem

- the action of giving thanks for a comment is a little slow and can result in the user clicking it multiple times

#### Ideas / Proposed Solution(s)

- I think we should use "optimistic UI" here, meaning that we assume the operation was successful and update the UI immediately in order to have a better user experience and prevent confusion
- We can always display an error if for some reason the operation failed

**Comment by davidsonsns** [comment]
It'll be good to remember some apollo concepts. Could you assign it to me?

**Comment by robin-macpherson** [comment]
@davidsonsns absolutely! Thanks for taking it 😄🙏🏼 By the way, just to make you aware I will hopefully be completing a pretty big project re-org this weekend. It shouldn't be too bad hopefully since the PR for this issue should be quite simple but I just wanted to let you know 🙂

**Comment by davidsonsns** [comment]
That sounds amazing!

Don't worry I'll send a small one. Anyway, I was thinking about applying this same optimistic behavior to update and delete features. That sounds good? If so, I'll split it into more than one or. It will help with the reviews.

Is this refactor related to PR #400? Just saw it here right now. It'll definitely be helpful.

**Comment by robin-macpherson** [comment]
Yep it's based on the proposal in #400 😄

Regarding optimistic UI for updates and deletes, are you specifically just talking about for comments?

**Comment by davidsonsns** [comment]
Yeah, just about post comments

**Comment by robin-macpherson** [comment]
Ok sounds good! 💪🏼

**Comment by davidsonsns** [comment]
@robin-macpherson can it be closed?

**Comment by robin-macpherson** [comment]
@davidsonsns absolutely! Sorry for the delay 🙏🏼
