### ISSUE TITLE
Add a "Cancel" Button to post editing experience

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#442]
#### Perceived Problem

- Currently there's no clean way to cancel editing a post except just leaving the page

#### Ideas / Proposed Solution(s)

- Let's add a cancel button
- Include an "are you sure?" modal that explains unsaved progress will be lost
- Restore our auto-save local storage to the previous state to keep things in-sync next time the user goes to edit the post

**Comment by dom-waterson** [comment]
Hey I'd like to help out on this project. Thought this issue might be the best place for me to start.

**Comment by robin-macpherson** [comment]
@dom-waterson that's awesome! I just assigned the issue to you and also added a couple of extra bullet points to the description with a couple of things you'll want to account for. There are existing patterns in place for confirmation modals you can take a look at and hopefully everything will be quite straightforward, but please feel free to reach out if you need any help with anything and we also welcome draft PR's if you'd like early feedback. Thanks for contributing! 🙏🏼

**Comment by dom-waterson** [comment]
Thanks! I've made a start. Might put up a draft PR to make sure I've done the translations correctly. Going to get my head round how you guys use local storage on the edit post and to restore the post correctly.
