### ISSUE TITLE
EDITOR: Ability to include tables inside a post?

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#444]
#### Perceived Problem

- Some users have requested the ability to include tables inside their posts

#### Ideas / Proposed Solution(s)

- Let's see what Slate offers for this (slate.io docs & examples)

**Comment by robin-macpherson** [comment]
@davidsonsns just tagging you here so that it will let me assign you

**Comment by davidsonsns** [comment]
😁
