### ISSUE TITLE
chore: disable typescript-eslint/explicit-function-return-type

### ISSUE THREAD

**Issue by davidsonsns** [Journaly/journaly#446]
#### What

- Disable the lint warning `Missing return type on function.eslint@typescript-eslint/explicit-function-return-type`

#### Why

- As TS infer the return type. There's no reason for following with this warning.

#### How

- Adding the rule `"@typescript-eslint/explicit-function-return-type": "off",` on the file `.eslintrc.js`;

#### Screen
![Screen Shot 2021-01-12 at 21 38 33](https://user-images.githubusercontent.com/9276511/104391421-9a3cfc80-551e-11eb-9bba-17a4589e86d8.png)

**Comment by robin-macpherson** [comment]
Thanks for the issue @davidsonsns ! 👍🏼
