### ISSUE TITLE
Make it clear a user needs to add languages if dropdown is empty on new post

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#451]
#### Perceived Problem

- Some users see an empty dropdown when writing a new post due to having not added language info yet in their settings and think this is a bug

#### Ideas / Proposed Solution(s)

- Let's change the placeholder if it's empty to help them understand why it is empty and what to do next

#### Screenshots

![image](https://user-images.githubusercontent.com/34203886/104751548-66bec580-570a-11eb-9121-691ad4790c29.png)

**Comment by rickyweb** [comment]
If the user has not yet defined any languages and clicks on "New Post", directly redirect him to the settings and highlight the section with the languages, add a message "Please select at least one language with your level of knowledge in order to write your first post".

**Comment by dom-waterson** [comment]
Hey guys I can take this one if you don't mind. This did confuse me at first too. Solution just to update the placeholder text to something like "Please select at least one language in settings" if userLanguages is empty?

**Comment by robin-macpherson** [comment]
Thanks @dom-waterson ! Sorry for the slow reply, I've had a difficult last week so wasn't able to get to this sooner. I just reviewed your PR and left a comment 😊
