### ISSUE TITLE
Include search filters on "My Posts" page

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#452]
#### Perceived Problem

- Some users who have written a lot of posts have reported that it would be helpful to have the filters on the My Feed page also in their My Posts page

#### Ideas / Proposed Solution(s)

- Fortunately, we've already refactored the filters out into `FeedHeader.tsx`
- Let's include that on the my posts page

**Comment by robin-macpherson** [comment]
@meredithcat just in case you're looking for something else to work on right away, I think this could be a great candidate 😊

**Comment by meredithcat** [comment]
I'll take a look!

From a UI standpoint though, I think it would be good to hide the filters behind a "Show Filters/Hide Filters" button, to keep it from looking too cluttered. I'll look into how to do a show/hide animation but let me know if you already have something in mind.

**Comment by robin-macpherson** [comment]
@meredithcat I would say let's just keep it simple with adding the filters as they are for now because #617 handles those UI improvements.

**Comment by meredithcat** [comment]
Currently, `FeedHeader` does not include the filters - only the user greeting at the top of the feed. Should this feature include a refactor to add the filters to `FeedHeader`? Or is that part of another feature that hasn't yet been merged?

**Comment by meredithcat** [comment]
@robin-macpherson On second thought, maybe it would be better to create a `FeedFilters` component, since we explicitly *don't* want to include the header on the "My Posts" page. Let me know what you think - since you are working on a filters refactor in #617 maybe it could wait until after that.

**Comment by robin-macpherson** [comment]
@meredithcat let's just hold off on this one and I'll let you know when the approach is ready for #627 .
