### ISSUE TITLE
Build the Settings page

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#46]
#### Perceived Problem

- The settings page hasn't been finished yet

#### Ideas / Proposed Solution(s)

- Port over any completed or reusable code from the old repo
- Build out the page and all of its components

#### Designs

Hi-Fi - Limited

![image](https://user-images.githubusercontent.com/34203886/78512012-f84ddf80-7755-11ea-9f75-abe3e3101a2f.png)

![image](https://user-images.githubusercontent.com/34203886/78512048-4a8f0080-7756-11ea-83f6-af64f0120d28.png)

Wireframe:

![image](https://user-images.githubusercontent.com/34203886/78512079-7f02bc80-7756-11ea-84d2-df788e3bfebc.png)

**Comment by nlitwin** [comment]
@robin-macpherson how do you think we should position the breadcrumbs (`Settings > Edit Your Profile`) and the tabs (`Profile Info`, `Settings`, `Subscription`) for mobile? I think the breadcrumbs can stay up top, but not sure how the tabs will work
