### ISSUE TITLE
Daily Digest Email Improvements

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#460]
#### Perceived Problem

- We got v1 of the daily digest email out the door! 🙌🏼
- Currently, the email does not count comment thanks, which means we are still sending an email every time somebody received a thanks
- We could add more information to the email to make it even more helpful

#### Ideas / Proposed Solution(s)

Let's add:
- a `thanksCount` to the email
- the post image next to each comment
- the author name to each comment
- the time/date next to the comment

**Comment by rickyweb** [comment]
It's great to see work being done on this topic. Will there be a way to select in one's profile whether one gets individual e-mails or digest messages? I set up a filter which files all journaly messages in one folder, so I have the advantage of being informed right away when an interaction happens, without being flooded with messages in my main inbox.

**Comment by robin-macpherson** [comment]
Hey @rickyweb ! Yes in the future there will be notification settings that can be configured.

For now, I just created a PR that will make all of the improvements described in this issue and I think it greatly improves the daily digest email! I'm hoping to get this merged in today within the next few hours.

Soon we will work on adding the "in-app" notification feed so that users can have visibility into any activity right from inside the app, then we will begin building out the notification settings, starting with "on/off" and then more fine-grained settings such as daily digest, weekly digest, and so on 🙂
