### ISSUE TITLE
BUG: Impossible to write or edit Korean text on mobile

### ISSUE THREAD

**Issue by rickyweb** [Journaly/journaly#479]
|                    |                      |
| ------------------ | -------------------- |
| repro              | [link](https://todo) |
| `node` version     | `...`                |
| OS and its version | `android 6.x with Microsoft SwiftKey keyboard 7.7.0.4`                |

#### Description
When typing the Korean characters, one composes syllables letter after letter. So when writing 한국 (Korea), one types the following characters in this sequence: ㅎ,ㅏ,ㄴ,ㄱ,ㅜ,ㄱ. This has the following output:
ㅎ
하
한
한ㄱ
한구
한국

Now, when typing in the title box, everything works fine:
![Screenshot1](https://user-images.githubusercontent.com/2961791/105811953-a8265f00-5fad-11eb-9bc0-81583c46cd98.jpeg)

#### Repro Steps

However, when typing in the compose text field, things get very spooky, especially when you use backspace in order to delete a character.
1. Assume, you just wrote 하,
2. delete the ㅏ (in order to get back to just ㅎ, because you in fact wanted to write 호.) When deleting the ㅏ,
3. you get an error message:
![Screenshot2](https://user-images.githubusercontent.com/2961791/105811956-a8265f00-5fad-11eb-886e-939b033ff4ff.jpeg)
4. When you go back, you get this text:
![Screenshot3](https://user-images.githubusercontent.com/2961791/105811952-a78dc880-5fad-11eb-8412-d60cf4a37d15.jpeg)
5. And if you select everything and delete the whole selection, you get this output.
![Screenshot4](https://user-images.githubusercontent.com/2961791/105811949-a6f53200-5fad-11eb-912b-d999d4f30886.jpeg)

This makes it impossible to write in Korean.

As this is only happening with this web application, I believe the problem is not related to the mobile phone nor the keyboard used, but some "magic" happening when entering text, magic that works well in all other languages, but has these unwanted effects in a language with composed keystrokes like Korean.

**Comment by Lanny** [comment]
Yeah :( ...

This is an upstream bug in slate, which is supposedly an upstream bug in chromium. It effects, AFAIK, every character composition based IME. Which is really really bad for a language learning app. It varies in severity depending on OS/browser it seems. We haven't had time/resources to go poking around in slate but that does seem to be where the fix needs to happen.

I have a theory that the placeholder text is what's responsible for the full crash scenario, #484 removes that so if you want to test on the preview env that's spun up for that and post your findings that would be helpful, although I don't think it's going to be a total fix.

Issue #194 is related.

**Comment by rickyweb** [comment]
@Lanny, that's really bad news... I've checked on preview and, unfortunately, there's no change. I've now found out that the sequence I had described above was not exactly correct. Here's what I noticed now on preview:

1. type ㅎ
2. type ㅏ
3. this gives 하 and the page automatically loads the 404 error
4. Now when going back to the new post, I can see ㅎ(line break)하
5. If I put the cursor after ㅎ and hit backspace, the spurious letter actually gets deleted.
6. without moving my cursor, my keyboard suggests 한국어
7. If I select this word, I see very briefly 한국어(line break)하 then I immediately get the 404 error again
8. If I go back, I can see 한국어ㅎ(line break)하

Whenever I wrote about "going back" above, I actually mean, using the back button of the browser, which leads me to the page I was on before creating the new entry, then I click on the Menu Burger> New Post.
8. If I go back to the new post, I can see ㅎ한국어하

**Comment by candacepowell** [comment]
Hi @Lanny, 

A user has reported this for Urdu, also. 
Would you like their specific experience details, too, or we're confident it is all IME?

**Comment by Lanny** [comment]
Pretty confident it's all IME that involves substituting characters while typing, but if it's easy to just copy paste the details in here it never hurts to have more. If you need to get more info from the user though it's probably fine to not bother them and simply note that it's a known bug.

It's really lousy but copy pasting content is probably the best workaround users have at the moment. I think there's some variability in OS/browser as well (I think safari is less severely affected?) but I don't remember if there's any browser where it's perfect (and recommending using another browser kinda sucks too)

**Comment by candacepowell** [comment]
Fair call, and agree. Interestingly, some new insight from another user came through today:


_"I wanted to let you know a glitch I’ve noticed when typing accented characters using OS X shortcuts (option-E for ´, option-U for ¨, then the letter to create accented letters like é, á, ü, ä, ñ, etc) that as soon as the second letter (the one over which I’m trying to put an accent) has been typed, the accented letter appears where it should but the text cursor jumps to the beginning of the paragraph. This does not happen with similarly-shortcutted one-step letters like ß (option-S) or ç (option-C) so it’s not a bug from using the option key or a non-English keyboard but something related to the two-step process of creating áéíóúäöüñà, etc."_

They also reported this _"does NOT occur when typing in the title of a post or adding a comment on someone else’s post, just when typing in the main text area."_

Please also let me know if I'm not being concise enough or if you don't need any further examples, and I can manage the users until we have a solution and leave you in peace hehe

**Comment by Lanny** [comment]
No no, plenty concise! And good to know this. I didn't realize it was happening with accented characters as well but it makes sense that it does, but not with characters that are input with one keystroke + modifiers. The central problem, from what I gather from the slate repo, is around IME inserting a symbol (e.g. the accent mark with nothing under it, or an incomplete syllable block in hangul), and then swapping that symbol out for another when the next part of the composition comes in.

**Comment by candacepowell** [comment]
@Lanny and @robin-macpherson - this issue prevented a user from signing up. 
I was able to navigate them to use non-accented characters for their username and they were successful.

**Comment by robin-macpherson** [comment]
@candacepowell the issue that user had signing up was unrelated to this bug. This bug is only related to things that happen in the Journaly Editor and it's also just about character input itself (so problems actually typing and inputting certain characters). Her issue was simply about using characters that are currently unsupported for handles, I'll file an issue to improve the guidance a user sees and discuss other possibilities.

**Comment by candacepowell** [comment]
@robin-macpherson - Ah! Makes sense. Thank you for clarifying the difference.
