### ISSUE TITLE
Build Post Liking

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#480]
#### Background

There are two different concepts at Journaly that are often a single concept of "liking something" on many apps:

1. the concept of "thanks" which we associate with inline feedback comments where you can say thank you to someone for a piece of feedback
2. the concept of "liking" a post in general

We want to be able to incentivize and reward helping fellow community members, and we also want a way that high-quality/helpful feedback can be identified over low-quality/less helpful feedback. This concept of being able to say "thanks" for a feedback comment created a way to do this, also allowing us to aggregate data about things like how many "thanks" a user has received as one measure of how much help they have contributed to the community.

This differentiation allows for "liking" a post to be a little more generic. It's a way of indicating you like something, and also the popularity of a post without this impacting the previous concept of thanks and a user's related statistics.

#### Perceived Problem

- Currently, the functionality for liking a post is not yet built
- Because we display the lake count in the postcards in the feed, and also a users profile, It can be confusing for some users who might think this is supposed to be related to the number of thanks that have been given/received inside of a post
- Currently the same icon is used for thanks and also the lake account, which can further lead to confusion

#### Ideas / Proposed Solution(s)

- I would like to find two separate icons for thanking and liking To help us more strongly differentiate these two concepts with our visual design language
- I've struggled quite a bit figuring out what icons would be best for this.
  - I thought about prayer hands which I quite enjoy using myself colloquially, but these have a religious connotation that make them potentially inappropriate for a global and inclusive platform
  - So far for thanking, the heart seems like a reasonable choice
  - For liking, I wanted to pick something else that is not the thumbs up. This is another gesture which can mean different things in different cultures, and also feels very Facebook-y 😒
  - As a short term solution, I thought about using a star for the liking concept, although this has been used a lot for the idea of a favorite on other platforms

**Comment by robin-macpherson** [comment]
@Lanny going to try to work on this soon as it's one of the last foundational loose ends in the UI to tie up (in that the concept is there but not the functionality). If you have any last thoughts on the iconography/visual language for communicating the two concepts of thanking vs. liking please let me know, as I'm still not super happy with these options - particularly what icon to use for "liking" something - but we need at least something for a first iteration so that things at least work.

Also curious to know if you have any thoughts @Candace

**Comment by candacepowell** [comment]
Definitely agree with the design and conceptual approach, in differentiating Journaly from other platforms (promoting our culture and values over general practices) while acknowledging different cultural connotations. 

I can appreciate how choosing iconography that represents these ideas has been a little tricky! And especially as these concepts (eg: Badges) will have the potential to become more sophisticated.

For "liking" would we consider something non-traditional and more on-brand? (I shudder as I write that) .
..Something like a quill? 

![Example Quill](https://user-images.githubusercontent.com/77520576/106071513-91713b00-615a-11eb-9c3f-0752392a729f.jpg)
