### ISSUE TITLE
Can't upload avatars/profile images

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#482]
Original report:

```
Hi Robin,
I was looking for where to ask technical questions/report anything technical on Journaly.
Could you tell me where I should send that kind of messages please?
Btw, it's nothing big, don't worry. Just been unable to upload a profile picture
(I've tried while bejng connected to different wifis, tried several file sizes down to rather small but it keeps loading forever so I thouht maybe something is wrong with that feature) .
Btw, I am LOVING Journaly!!!!!!!!!!!!
```

Probably a result of thumbbuster changes.

**Comment by Lanny** [comment]
@candacepowell @robin-macpherson I wasn't able to repro this on prod. I tried on chrome and firefox on OSX. Can we reach out the folks reporting this issue and find out their OS/browser combos, and if we could get one of the images they're having trouble uploading that would be awesome

**Comment by candacepowell** [comment]
@Lanny @robin-macpherson - Done. Will let you know once I receive info back.

**Comment by candacepowell** [comment]
For what it is worth, I couldn't replicate this today either. 

macOS Catalina v10.15.7
Chrome Version 88.0.4324.96

**Steps to Reproduce:**
1. https://journaly.com/dashboard/settings/profile
2. Click "Upload Image"
3. Select file (see attached below)
4. Loading circle appeared for max 5 seconds
5. Notification received that image upload was successful (blue sliding bar)
6. Image saved on profile

![Me](https://user-images.githubusercontent.com/77520576/106337287-e93bad80-62e4-11eb-9d87-0e6fb4e753e3.jpg)

**Comment by candacepowell** [comment]
We have a reply from the user. 🙌🏼 

Chrome
Windows 10

_Images:_
![AVA-IslaMujeres](https://user-images.githubusercontent.com/77520576/106367867-e0f17a00-6399-11eb-97d9-e48d90266c36.jpg)
960 × 720, 45KB

![AVA-Learn ProfilePic](https://user-images.githubusercontent.com/77520576/106367913-47769800-639a-11eb-94ad-26a8e3ae224c.jpg)
511 × 515, 37KB

And they've also supplied two others which I can only save as .txt for some reason? But all 4 were unsuccessful.

**Comment by robin-macpherson** [comment]
Thanks for getting these @candacepowell ! 🙌🏼

**Comment by robin-macpherson** [comment]
Two posts that users have written publicly about this issue:
- https://journaly.com/post/3427
- https://journaly.com/post/3489

Also highlights urgency for #483

**Comment by candacepowell** [comment]
> Two posts that users have written publicly about this issue:
> 
> * https://journaly.com/post/3427
> * https://journaly.com/post/3489
> 
> Also highlights urgency for #483

User of Post 3427 has advised in the last 3 days their images were able to be uploaded. 
_"Finally I can upload images. With my usual browser (Chrome)I could not upload, there after choosing the image I had the hourglass forever. Just now I had the idea to try it with a different browser (Edge) and, yippee, with this browser it works just as expected."_

This issue relates to avatar/profile images and also post banner images.

**Comment by candacepowell** [comment]
Additional User feedback: 

**1. What browser are you using?** 
I'm mostly using Google chrome on my PC although I'm not sure what version. 
**2. What operating system are you using? (for example: Windows 10 or MacOS Big Sur)** 
I'm using Windows 8.1 64bit
**3. What is your journaly handle or the email address for your account?**
My e-mail address is knightghost1@gmail.com
**4. Which posts did you attempt to upload images for and failed?**
 These are the posts
- Estaba tratando de ... https://www.journaly.com/post/3145 
and
- Medddyliau wythnos . - Dydd 1 https://www.journaly.com/post/3600

**Comment by robin-macpherson** [comment]
Very hapappy to be closing this! 🙌🏼
