### ISSUE TITLE
Include support email address somewhere on the site

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#483]
a limited subset of users have access to the bug report spreadsheets, a lot of users use YT or IG to reach out for support, but this doesn't scale as we take in more users from other channels. We now have a lovely support email address with some top notch people responding to emails so we should get that out there and direct people to it.

Discoverability seems like a bit of a challenge, not sure we want to put this on the nav since that's prime real estate, but since the home page is inaccessible to logged in users that doesn't work either. Maybe an "about" entry on the sidebar that will take us to another page that includes support info and we can throw other static content into, e.g. an FAQ or something.

Adding this to premium milestone since making sure people can get in touch is going to be important to have before we start taking in money.

@robin-macpherson

**Comment by candacepowell** [comment]
Love this idea and it deeply couples with high volume feedback from users across multiple platforms.

I think the idea of directing traffic to a dedicated space is also smart, as we start expanding user-facing information too. 

Apologies in advance for my development-effort ignorance, but Notion has a pretty intuitive yet discrete support feature that sits in the bottom-left whatever page you're in. It sits as a (?) and then pops out, as shown below:
![Notion Support Example](https://user-images.githubusercontent.com/77520576/106224009-97d4e500-6236-11eb-8cdf-05c43ad904e3.jpg)

**Comment by Lanny** [comment]
Ah, nice prior art! I like the notion approach, doesn't take up too much space but it gives us some room to add additional content, I feel like a question mark should be fairly universal iconography (although that might be something worth checking) that signals support. 

One thing I will say is the placement of the actual support button is not my favorite. Controls that float over content are a pet peeve of mine (they tend to get fat-fingered a lot, and can obscure content) and we have content that's edge to edge up until like 1700 pixels horizontally. Also on mobile they remove the floating button and add an entry to their hamburger menu, and if you select it you get a slide-up modal, so it's kind of like a double modal experience which works but modal stacks have always seemed messy to me:

![Screen Shot 2021-01-29 at 11 28 51 AM](https://user-images.githubusercontent.com/2343714/106307626-30626980-6225-11eb-940f-1852aa0347d6.png)

Maybe a sidebar entry that has the notion style fly-out menu on large/mid, and maybe an accordion style expand/collapse on small screens?

**Comment by candacepowell** [comment]
`Maybe a sidebar entry that has the notion style fly-out menu on large/mid, and maybe an accordion style expand/collapse on small screens?` I like the way you're going with this. 

The scope of this work may quickly blow out, which I think we should be conscious about. Already the idea has shifted from an email address to the full support suite... 😅   

How about I come back in the next 24 hours with some functional requirements for each Help/Support/About entry? That will give us some clearer scope and we can then discuss priorities, solution design and chunking this work.

@Lanny @robin-macpherson Thoughts?

**Comment by robin-macpherson** [comment]
Hi chaps sorry have only had a chance to very briefly skim the thread so far but how about as a first step just a button/question mark that simply pops up a little modal that simply says something like "Need help? We've got you! Please email hello@journaly.com with <insert requirements> and we'll get back to you as soon as we can!" ?

Something like that could be very simple to build since we already have the modal stuff built and it would simply contain text with instructions to email us. The biggest pain-point users have had seems to simply be not knowing how/where to reach out for help or to report issues, etc. and I think this would solve that for now!

Just my $0.02!

**Comment by candacepowell** [comment]
Addresses the immediate user need and leverages existing modal work. Smart! 

"Need help? We've got you! Please email hello@journaly.com -with- and we'll get back to you as soon as we can!"

This also decouples the requirement from the other support stuff discussed.

**Comment by Lanny** [comment]
Haha, yeah, good point, we don't need to worry about submenu-ing concerns at this point. Question mark on the sidebar works for me

**Comment by robin-macpherson** [comment]
Awesome, I can try to get this done tomorrow (Sunday) 🤞🏼

**Comment by candacepowell** [comment]
Well done! Looks slick!
