### ISSUE TITLE
Build mechanism for preserving a user's search filters throughout a session

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#490]
#### Perceived Problem

- Currently, ever user selects a combination of filters and then navigate away from the feed page, for example to read a post, when they come back to the my feed page the filters are reset
- This has actually been one of the most reported feature requests out of things we haven't built yet. It seems that a lot of users expect the filters to be preserved throughout a session or at least after some simple navigation between posts and back

#### Ideas / Proposed Solution(s)

- Building mechanism for retaining the selected filter combinations

**Comment by robin-macpherson** [comment]
@candacepowell just pinging you so that you know this is here as I know we're getting a lot of support requests about it. I'll also plan to post an approach doc for the technical design of this over this weekend ✨

**Comment by candacepowell** [comment]
Excellent. Thanks for doing this. It was on my list for today, as I recalled seeing a similar ticket here for "related" posts and wanted to re-read to wrap my head around how similar or technically different they were, so I wasn't duplicating a ticket. 

Love it, and agree with the medium priority. I've been proposing that users open each post in a new tab for now (where possible, as a temporary way to work around this).

**Comment by Lanny** [comment]
Good stuff, can probably just stuff a value in local storage or session storage. Heck, just keeping the filter set in `useAutosavedState` might get the job done.

I don't think we ever made a ticket for it, but we discussed moving filter params into the querystring to make things like bookmarking filter sets possible. Probably not high priority, but if it's easy to add during implementation that would be cool

**Comment by robin-macpherson** [comment]
> I don't think we ever made a ticket for it, but we discussed moving filter params into the querystring to make things like bookmarking filter sets possible. Probably not high priority, but if it's easy to add during implementation that would be cool

@Lanny Yep that's the approach I was thinking of documenting in a quick approach doc today!
