### ISSUE TITLE
Mobile editor buttons overrun their container

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#494]
![Screen Shot 2021-02-06 at 5 20 16 PM](https://user-images.githubusercontent.com/2343714/107131836-b6268a80-689f-11eb-8df2-63ee11638879.png)

Seems to happen at most portrait mobile resolutions

**Comment by robin-macpherson** [comment]
Yeah looks like the extra buttons pushed us over. For the visual design, rather than simply wrapping I propose popping them onto two lines at mobile widths, with 5 on top and 4 on the bottom
