### ISSUE TITLE
Bust the cache after creating a new post

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#496]
#### Perceived Problem

- Currently, in production, when a user creates a new post and then visits there "my posts" page, they don't see that new post because of our Apollo cache.
- This is causing some users to think that we lost their post completely. In some cases the user ends up creating multiple duplicate posts trying to figure out what's happening.

#### Ideas / Proposed Solution(s)

- We should bust the Apollo cash whenever someone creates a new post to ensure they see the updated data when visiting the feed or my posts page

**Comment by davidsonsns** [comment]
Hi guys! Finally, I'm back!
I'd like to get this one. Could you assign it to me? Sounds that it won't take so long to be fixed, with that I can help with anything else after fixing an in-production bug.

**Comment by robin-macpherson** [comment]
Thanks @davidsonsns ! 🙏🏼 I've assigned it to you. Are you still planning to take #434 ?

**Comment by davidsonsns** [comment]
Lol! For sure I can do it, definitely forgot it. 😒

Thanks for reminding me!

**Comment by robin-macpherson** [comment]
lol awesome thank you @davidsonsns ! 🎉 By the way, I wanted to make you aware of this big project re-org just went in finally! 🎈 #497 

I'm going to be working on payments infrastructure next and Lanny is working on inline post images (our first premium feature). I do have a really exciting project for you next if you have more time after the current things 😄 🔥

**Comment by davidsonsns** [comment]
Of course, I'm game! Thanks for your feedback about all these new features.
That sounds great! I'll be very happy to keep contributing with you guys on the project.

**Comment by robin-macpherson** [comment]
Wonderful, it's been really great to have your help! 😄 So the next project I was thinking could be great for you after this and #434 is **Adding markdown support for commenting:** #425 – that one is going to be a HUGE improvement to the app and user experience! Let me know if it sounds like something you'd be excited to work on 😀

**Comment by davidsonsns** [comment]
Yeah! That sounds great @robin-macpherson.
Just saw your amazing work related to the structure. I have some points that could improve it even more (at least I think so 😇). I'll create a PR related to it ASAP.
