### ISSUE TITLE
Bug: Unable to view comment threads on feedback provided within tables

### ISSUE THREAD

**Issue by candacepowell** [Journaly/journaly#505]
|                    |                      |
| ------------------ | -------------------- |
|Post in Repro| [link](https://journaly.com/post/4306) |
| `node` version     | `...`                |
|OS and its version |macOS Catalina v10.15.7|
|Browser|Chrome|

**Description**
Users unable to view threads on feedback provided within a table

**Repro Steps**
https://user-images.githubusercontent.com/77520576/108572350-394ae480-7366-11eb-8af6-054180dab4a3.mov

**Comment by robin-macpherson** [comment]
Thanks for the report @candacepowell ! Moving this to high priority cc: @Lanny @davidsonsns
