### ISSUE TITLE
[web] - duplicated dependencies

### ISSUE THREAD

**Issue by davidsonsns** [Journaly/journaly#517]
I just ran the application with `yarn`(an automatic action, because of my work where we're using it) and saw this.

![Screen Shot 2021-03-06 at 20 44 45](https://user-images.githubusercontent.com/9276511/110224770-4e268c80-7ebd-11eb-88a7-3c944075a3d4.png)

**Comment by robin-macpherson** [comment]
Thanks for this one @davidsonsns ! 🙏
