### ISSUE TITLE
Paragraphs render inconsistently between editor and post

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#531]
Paragraphs in a post when you're reading it get a margin that isn't applied in the editor. This leads to situations where a user will enter two new lines (creating an empty paragraph) between two paragraphs to provide appropriate space between paras in the edtior, however when the post is rendered for readers, the space between paragraphs will be significantly greater than what they say in the editor.

Two obvious ways to fix this:

1. Apply the margin between paragraphs in the editor, so the editor accurately reflects what a published post looks like today. If we take this route, we should probably bump the amount of margin applied in both cases as paragraphs without an empty line between them look a little crowded today.
2. Remove the margin in the rendered post, again making the two consistent.

Personally I'm in favor of 2. since I'm accustomed to adding a blank line between paragraphs as a general habit when typing, editors assuming how I want to space paragraphs (or assuming every newline means new paragraph) kind of annoy me, but that might just be a me thing. This also gives a little more flexibility as it allows a post author to put two lines right on top of each other by not putting a empty line between them, if they want to do that for some reason (perhaps when enumerating things in a list, or if they want to push content very close to an inline image or table).

The downside of 2. is that folks that are not in the habit of spacing paragraphs out with an empty line will end up with tightly packed paragraphs.

**Comment by robin-macpherson** [comment]
Thanks for converting this to an issue @Lanny! I agree with taking approach #2, I think this is one of those things where users will learn how to deal with this as we've seen them adapt and adjust already. I can also include this in our next update video!
