### ISSUE TITLE
Feature: Community Guidelines

### ISSUE THREAD

**Issue by ghost** [Journaly/journaly#536]
**Perceived Problem**
While Robin does an exemplary standard of best practice in communication and community building just by being who he is, the platform is currently without formal guidelines of user behaviour, so our rights to act are somewhat limited in how the community is managed or reinforced.

**Ideas / Proposed Solution(s)**
- Simple and clear Community Guidelines modal that pops up on next log-in for all users
- Accept / Decline acknowledgement record??
- Available elsewhere on platform for reference at a later date - Settings for now?
- Must be aligned the simplicity, design, warmth and vision of Journaly
- Ability to hyperlink to support email address - hello@journaly.com

_Drafted Guidelines available in Notion - currently in review._

**Comment by candacepowell** [comment]
I fully appreciate this has a knock-on effect to other things, such as:
* Notifications of change
* Guideline breach management and alerting

...which can be created in separate tickets in due course.
