### ISSUE TITLE
User Learning Language Greeting Is Falling Back To English

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#538]
#### Description

Greeting is supposed to randomly select a language the user is learning to greet them in, unless they aren't learning a language or we don't have a translation. However, it only displays in English for me every time.

![image](https://user-images.githubusercontent.com/34203886/114281668-848f8400-99f4-11eb-8cab-3b73d733a255.png)

#### Repro Steps

1. Load the feed!

**Comment by meredithcat** [comment]
I tried reproducing this issue locally, and it is working for me as long as I add Dothraki and Valyrian to `components/Dashboard/MyFeed/greetings.ts`. Is there a SQL snapshot I could use that is closer to the production data, to get more info on what is happening?

**Comment by robin-macpherson** [comment]
@meredithcat I can get you an SQL snapshot, I'll send you an email 📧
