### ISSUE TITLE
Upgrade next-i18next

### ISSUE THREAD

**Issue by Lanny** [Journaly/journaly#543]
As of writing we're two major releases behind. Nothing is broken but this error we get a dozen times on every build:

```
18:43:50.519 | Read more: https://err.sh/next.js/opt-out-auto-static-optimization
-- | --
18:43:50.519 | Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
```

appears to be the result of their HoC and the current version does not seem to have the same issue. Think this should be a fairly straight forward upgrade, but possible there's some API change in there that could cause problems. Just smoke testing the German translation should be fine.

**Comment by robin-macpherson** [comment]
Closing this due to the decision to phase out this library 🚮
