### ISSUE TITLE
🌁 FEATURE: Build Unsplash Integration 📷

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#558]
#### Perceived Problem

- Posts definitely look nicer and more unique/personalised when the user uploads their own image but:
  - some users might not have a photo on hand that works for their post
  - it may feel inconvenient to have to go off and search for an image off-platform
  - many users may not know good places/websites where they can find images
  - we still have some open questions about users grabbing copyrighted images and uploading them

#### Ideas / Proposed Solution(s)

- Let's build an Unsplash integration that works very similarly to Notion's
- User's should be able to choose to either upload their own image or search Unsplash  within our UI
- This makes it incredibly easy and convenient to find images for your post without leaving the platform and without needing to have your own images or go out and take one, unless that's your thing!
- Actually saves us money and storage in AWS since we're just storing the URL to Unsplash's image and not uploading one & transforming it with Thumbbuster
- Increases the likelihood that people who don't have their own images end up using copyright-free images
- It would be good if this could also be extended/available to use for inline images as well

#### Open questions/concerns
- We need to take a look at pricing for the Unsplash API and see if we actually incur a larger cost for using the API than we'll end up saving in S3 storage or whether we think this could become a very expensive feature
- If this would end up potentially being very expensive, we may have to hold off

**Comment by robin-macpherson** [comment]
UPDATE: the API is completely free to use 🤯

**Comment by robin-macpherson** [comment]
Awesome, sounds great! Maybe you can go ahead and start playing with the API and exploring Notion's UI anytime now then and I'll get back to you in terms of starting. I'm sure you'll kill it with implementing everything and then we may just need to work collaboratively on the final UI/UX once everything's in place and working 😄 It would be absolutely amazing to get this in the platform!

**Comment by robin-macpherson** [comment]
Hi @dom-waterson ! I just wanted to check on the status of this one. Also, you'll want to update your branch as we just merged in tons of code with the new In-App Notifications System 🙌🏼

**Comment by dom-waterson** [comment]
Hi @robin-macpherson, Sorry I've had a busy few months. I did managed to get a "working" prototype back in Oct. Will update my branch and get it working again. Will open up a draft PR so you guys can see what I've done so far. I will be allocating some more time to work on it 😄

**Comment by robin-macpherson** [comment]
Thanks for the update, @dom-waterson ! Awesome yeah a Draft PR would be amazing so we can have a good idea of where things are, looking forward to seeing it! Also, I'm going to be making a big Journaly update video at the end of the month for the 1-year anniversary since we went into public beta - just for planning purposes, is the work at a point where you think we could start the collaborative refinement process (in terms of code review, design feedback, etc.) in the next week or so, or is that unrealistic?

It's no problem if not, I'm just planning ahead and figuring out what's likely to make it in before that big update.

Happy weekend!

**Comment by dom-waterson** [comment]
Hey @robin-macpherson got the draft PR up. Cool looking forward to watching the video! I would say it's possible but with me just starting a new job and the holidays, time to work on it might be tight so don't want to promise too much. But willing to give it a go 😄 

Do you have a slack or discord for contributors?
