### ISSUE TITLE
Proposal for modals

### ISSUE THREAD

**Issue by nlitwin** [Journaly/journaly#59]
For modals in our React app, we can make use of [React Portals](https://reactjs.org/docs/portals.html). This allows creating a separate "modal-root" element in the DOM, which is a sibling of the application root.

```html
<body>
  <div id="root" />
  <div id="modal-root" />
</body>
```

The parent `<Modal />` component can simply render `children` inside of it and all of it will be rendered in `div#modal-root`.

```jsx
<Modal>
  <div>I am the modal content</div>
</Modal>
```

The `<Modal />` component can be very minimal, with simple wrapping divs that handle animations, the blurred out background, and a close button. It will also handle rendering the modal in the center of the screen. The size of the modal and the content itself can be determined by the component passed in as `children` to `<Modal />`.

The main benefit to using React Portals is that the modal is not rendered as children to the content that triggers opening it. For example, your modal shouldn't need to be rendered in the DOM here:

```jsx
<Page>
  <button onClick={() => setIsModalOpen(true)}>Open modal</button>
  {isModalOpen && <Modal><div>Modal content</div></Modal>}
</Page>
```

**Comment by robin-macpherson** [comment]
Sounds great to me! Proposal ✅👌🏼 Let's put this in an approach doc as per the pattern I've set up for now so that we have them in version control.
