### ISSUE TITLE
User Research: Making Premium More Attractive

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#649]
### Description

We successfully launched Journaly Premium and got our first few users! 🎉 
However, it's clear at this point that we have a lot of work to do in making Premium more visible and attractive so that we can finally start bringing in at least enough revenue to comfortably sustain the project.

To start that process, let's conduct some initial User Research.
We'd like to reach out to our most active and enthusiastic users, since they may be most likely to be happy to help us figure this out and they also know the platform best. They also see a lot of interaction with other users, much more than we do!

Let's reach out to all users who have:
- written an average of 4 posts per month
  - currently 40 people

How do we want to do it?
- TypeForm
- Survey Monkey ✅

What do we want to ask?
- Have you heard about Journaly Premium before now?
  - If yes, where did you hear about it?
- Premium currently offers [a, b], were you aware of these Premium features before?
- Given the current Premium features, how much would you be happy paying?
  - 0
  - less than 5
  - 5
  - 7.50
  - 10
  - 15
- If Journaly had every feature you wanted, how much would you be happy to pay then?
  - 0
  - less than 5
  - 5
  - 7.50
  - 10
  - 15
- Do you pay for any other digital language learning products? If you don't mind sharing, what products?
  - Free entry
- What new premium feature would be most excited to see added to Journaly?
  - Post themes (aesthetic changes to posts, e.g. a "typewriter" theme where your post visually appears like a typewritten page)
  - Regularly updated rotating post prompts in your native language to help you find a meaningful topic to write about
  - Additional editor features like a "focus mode" to help you in writing posts
  - Other (feel free to write in anything, we want to build what you want to use)

### Steps

- [x] Write the query 
- [x] Create the survey
- [x] Write the email (be sure to `bcc`)
- [x] Send it out

#### Query ✅

```sql
SELECT "authorId",
               COUNT(*)
FROM "Post" AS p
WHERE "publishedAt" > NOW() - interval '84 days'
GROUP BY "authorId" 
HAVING COUNT(*) > 11 
ORDER BY count DESC;
```

#### Survey ✅
https://www.surveymonkey.co.uk/r/journaly-brainstorm

**Comment by meredithteo** [comment]
Just another idea - it might help to put a link somewhere prominent on the homepage that points to the premium subscription page - either as a bar at the top of the page, or as a permanent sidebar item, or just as a one-time modal that can be dismissed. As it is, it's easy to miss as it's kind of hidden in the user settings page. Ideally, the subscription page would also list which premium features are currently available and which are soon to be built out.

**Comment by robin-macpherson** [comment]
_Below is a summary of the most interesting responses & insights after sending the survey to our 50 most active and consistent users over the last four months._

## Results

**Responses:** 22 🎉

#### 1. Had you heard about Journaly Premium before this survey?
- **Yes**: 18 / 81.82%
- **No**: 4 / 18.18%

#### 3. Were you aware of all these Premium features before?
- **Yes**: 16 / 72.73%
- **No**: 6 / 27.27%

#### 4. Given the current Premium features, what do you feel would be a totally reasonable monthly price?
- **£0:** 5 / 22.73
- **< £5:** 11 / 50%
- **£5:** 4 / 18.18%
- **£7.50:** 2 / 9.09%
- **£10:** 0 / 0%
- **£15:** 0 / 0%

#### 5. ... If Journaly had all of these features along with any other feature you wanted, how much would you feel is a totally reasonable price then?
- - **£0:** 2 / 10.53%
- **< £5:** 5 / 26.32%
- **£5:** 7 / 36.84%
- **£7.50:** 4 / 21.05%
- **£10:** 1 / 5.26%
- **£15:** 0 / 0%

#### 6. What new premium feature(s) would you be most excited to see added to Journaly?
- **None of the above:** 3 / 16.64%
- **Post Themes:** 1 / 4.55%
- **Writing Prompts:** 7 / 31.82%
- **Focus Mode:** 1 / 4.55%
- **Other:** 10 / 45.45%

(Quite a few mentioned _Writing Prompts_ within their "other" answers as well, which was mostly used to provide additional suggestions).

## Insights

1. Many people don't even know that Premium exists - especially considering that almost 20% of even our most active users weren't aware!
2. Of those who do know about it, many aren't aware of all the features if offers.
3. We also see pretty much all of our hypotheses around pricing proven out:
  - Our current price is simply too high, even for a more robust version of Premium without substantial structural changes.
  - People's perception of a totally reasonable price is indeed quite different with our current features vs. a more robust feature set
  - Based on this initial data, it would seem our ideal price point may be **£5**. The majority of people chose £5 with a pretty even split on either side of it (< £5 & £7.50), with some even willing to pay £10. This tells me that while we could indeed get plenty of people to pay £7.50, many of them wouldn't be totally happy with that and we'd have far fewer paying customers. It seems that at £5, lots of people would be very happy, plenty of people would even feel like it was an amazing deal, and there would likely be plenty of people in the **< £5** segment who may still be willing to sign up, even if they didn't feel it was the ideal price point.
  - In terms of pricing, it's also worth noting that the people who chose £0 wrote later in the survey that this was either due to our demon J-Editor bug (IME problems 😭) or just basic things needing improvements in general before seeing paid value. One person said it was due to their country's political situation.
4. While _Writing Prompts_ was probably at the bottom of our list of the three next premium features to build, it seems that this one is the overwhelming favourite out of those three.

**Comment by robin-macpherson** [comment]
Thanks @meredithcat 😊 We have some work planned to make Premium much more visible, ranging from some of the things you mentioned to showing Premium features always but simply showing a little modal that "this is a premium feature" rather than hiding them completely, and also alongside the detailed feature lists also creating a few introductory videos - possibly even formatted as tutorials. And finally, actually using our email list occasionally – it's one of our largest expenses and we almost never email out of respect for people's inboxes, but I think we can totally experiment more with the occasional email along with one-time modals with a series of updates.

I think all of this should help a ton with just creating way more visibility ✨
