### ISSUE TITLE
Cannot view profiles when logged out

### ISSUE THREAD

**Issue by meredithteo** [Journaly/journaly#660]
#### Description

Often, I want to share my Journaly profile with someone who doesn't have an account, like my in-laws who are not so tech savvy but want to read my journal entries. It looks like this is currently broken, and shows the error: `An error occurred on the server`

#### Repro Steps

1. Log out.
2. Visit any profile page.

**Comment by LindasLinguas** [comment]
This is the error message I'm seeing: 

"Auf dem Server ist ein Fehler aufgetreten

Argument where of type UserWhereUniqueInput needs at least one argument."
