### ISSUE TITLE
Unauthenticated pricing page doesn't render text properly

### ISSUE THREAD

**Issue by Destaq** [Journaly/journaly#858]
Hi, just wanted to give a quick heads-up that the landing page seems to be broken. If you log out, and go to https://journaly.com, (at least in my case), the features hero section looks as follows:

<img width="1367" alt="image" src="https://github.com/Journaly/journaly/assets/61620873/8454a6a3-e9ee-4710-a97f-6512ffc444d0">

Probably not the intention? Tested on Safari and a Chromium browser alike, and the latter even in Incognito.

**Comment by robin-macpherson** [comment]
Ah yes, thanks for this @Destaq ! Some recent dependency updates have been causing issues with the translation strings. @Lanny I'll see if I can take a look here but looping you in just in case you have time to look before I do
